services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./earthquake-map
    container_name: earthquake-frontend
    volumes:
      - ./earthquake-map:/app
      - /app/node_modules
    ports:
      - "5173:5173"
